/** 
 * @file IceGenerated.hpp
 * convert ::mapreduce::slice namespace into ::mapreduce.
 * 
 * @author Zhifeng YANG
 * @date 2007-11-28
 */
#ifndef _ICE_HPP
#define _ICE_HPP 1

// headers generated by ice
#include "WorkerService.h"
#include "Address.h"
#include "MasterCommand.h"
#include "Heartbeat.h"
#include "JobService.h"
#include "MapReduceJob.h"
#include "MonitorService.h"
#include "TaskDetail.h"
#include "JobDetail.h"

namespace mapreduce
{
    using mapreduce::slice::Address;
    using mapreduce::slice::Addresses;

    using mapreduce::slice::WorkerService;
    using mapreduce::slice::WorkerServicePtr;
    using mapreduce::slice::WorkerServicePrx;
    
    using mapreduce::slice::MasterCommand;
    using mapreduce::slice::MasterCommands;
    using mapreduce::slice::Heartbeat;

    using mapreduce::slice::JobService;
    using mapreduce::slice::JobServicePrx;
    using mapreduce::slice::JobServicePtr;
    using mapreduce::slice::MapReduceJob;
    
    using mapreduce::slice::McDoNothing;
    using mapreduce::slice::McShutdown;
    using mapreduce::slice::McDoMap;
    using mapreduce::slice::McDoReduce;
    using mapreduce::slice::McDoTrans;
    using mapreduce::slice::McDoClean;

    using mapreduce::slice::MonitorService;
    using mapreduce::slice::MonitorServicePtr;
    using mapreduce::slice::MonitorServicePrx;

    using mapreduce::slice::TaskDetail;
    using mapreduce::slice::TasksDetail;
    using mapreduce::slice::JobDetail;
    using mapreduce::slice::JobsDetail;
    using mapreduce::slice::TasksStatistics;
    using mapreduce::slice::WorkersDetail;
    using mapreduce::slice::WorkerDetail;
}



#endif /* _ICE_HPP */
